// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalParties.DataLayer;

namespace PoliticalParties.DataLayer.Migrations
{
    [DbContext(typeof(PoliticalPartiesDbContext))]
    partial class PoliticalPartiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PoliticalParties.Entities.Development", b =>
                {
                    b.Property<long>("DevelopmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityMonth")
                        .HasColumnType("int");

                    b.Property<int>("ActivityYear")
                        .HasColumnType("int");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PoliticalLeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevelopmentId");

                    b.ToTable("Developments");
                });

            modelBuilder.Entity("PoliticalParties.Entities.PoliticalLeader", b =>
                {
                    b.Property<long>("PoliticalLeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("CandidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PoliticalPartyId")
                        .HasColumnType("bigint");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliticalLeaderId");

                    b.ToTable("PoliticalLeaders");
                });

            modelBuilder.Entity("PoliticalParties.Entities.PoliticalParty", b =>
                {
                    b.Property<long>("PoliticalPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Founder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliticalPartyId");

                    b.ToTable("PoliticalParties");
                });
#pragma warning restore 612, 618
        }
    }
}
